# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38b14e4b794e69e58d63231f480bbb38d19d88d07569856f8d7c6da5c94bde6f25e14fa55335dc5b87770f2fe3b8f766c1ba7e3a61b185bb25168100b9d32c98

test:
  secret_key_base: 09dd0a0b2bf04a350aff3a9f281ed350ffbf7cbb45e6ea5d25de9bae7fc82dab5db865767c2fc134ded532e15dea20b7a6f58ce4879149296d0f0a344cd8132f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
